# Generated by Django 4.2 on 2023-04-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_apis', '0005_ecg_data_altitude_ecg_data_ecg_arr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecg_data',
            options={'ordering': ['-date_time']},
        ),
    ]
